### PR TITLE
Fix the up value to match the tree depth of the source file

### PR DESCRIPTION
**Pull request by JensLuyten**
When copying files from a source folder into your theme folder structure, the copy command also copied the parent folders the source file was in. This occurs since v0.4.0 of Buildozer.

Example:
`copy:`
`  - src: node_modules/bootstrap/dist/js/bootstrap.min.js`
`    dest: source/scripts/all`

resulted in the following folder structure:
`source/scripts/all/node_modules/bootstrap/dist/js/bootstrap.min.js`

By setting the `up` value to the length of the src path minus 1, only the file is copied into the folder declared in the dest argument of the copy settings. This change will put the file in `source/scripts/all/bootstrap.min.js`.

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
@JensLuyten, can you write a test for this?

**Comment by JensLuyten** [comment]
@MartijnCuppens, I have added a test for this copy use-case.

**Comment by MartijnCuppens** [comment]
@JensLuyten, these tests can be combined with the existing `test-copy` (just combined these).

I've also added some additional tests which show this is still not fixing every case (especially when globbing is used).

**Comment by JensLuyten** [comment]
Hi @MartijnCuppens 

I've refactored the copy command to be able to work with globbed src definitions. It will now copy files per path rather than per defined location.

Only concern with that one may be performance, but not sure how much it will be affected.

**Comment by MartijnCuppens** [comment]
I've moved the logging to a separate function which is a bit clearer.

> Only concern with that one may be performance, but not sure how much it will be affected.

I don't think this will affect performance much.

**Comment by JensLuyten** [comment]
Yeah fine, looks a lot cleaner now indeed. :)

**Pull request merged**
